### ISSUE TITLE
Faltan miembros por unirse

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twQ103-trivial#1]
Faltan Carlos y Sofía por unirse, recuérdales que deben hacerlo a través de moodle en la sección Trabajo en Equipo. Si no lo hacen los profesores no les van a poder ver en el equipo ni calificar

**Comment by MPerezMateo** [comment]
Sofía ya esta unida, solo falta Carlos, parece que los enlaces sí que funcionan a pesar de aparecer esa nota en rojo. @Aitana-C  @SophiaVillanova

**Comment by Juliauru** [comment]
Perfecto, ya estáis todos.
